### ISSUE TITLE
Request update zstd to 1.5.5

### ISSUE THREAD

**Issue by BlackHole1** [drakedevel/zstd-napi#3]
Hey @drakedevel 👋. Thank you for creating this library, it has been very helpful to us. However, zstd has now released version `1.5.5`. I tried building it myself but was unsuccessful.

Ref: https://github.com/facebook/zstd/releases/tag/v1.5.5

**Comment by drakedevel** [comment]
Hi! Glad to hear the library has been helpful 😀

I'll try to get a build with the latest zstd up in the next couple of days. It's actually been on my to-do list for a while, so thanks for the nudge!

**Comment by BlackHole1** [comment]
@drakedevel Thanks!

**Comment by drakedevel** [comment]
@BlackHole1 Just published v0.0.7 based on zstd 1.5.5.

If you have any other feedback from using the library -- rough edges, performance issues, features you'd like exposed, etc. -- I'd love to hear it!

**Comment by BlackHole1** [comment]
@drakedevel Wow! Thank you so mush for your work! I will upgrade it later. This library is great for me, and I have learned a lot while reading the source code. Thank you again!
